### ISSUE TITLE
Password input is unmasked

### ISSUE THREAD

**Issue by dluciv** [denis-sokolov/chrome-supergenpass#87]
Denis, thank you very much for your beautiful extension! Really useful one.

The only issue I see now is when it asks for the password ("SuperGenPass for Google Chrome™ by Denis" message box), password is displayed unmasked. I guess it is better to `*****` it.

Tested with recent x64 Google Chrome and Iridium on Windows.

It is likely here: https://github.com/denis-sokolov/chrome-supergenpass/blob/master/src/lib/storage.js#L127

I guess it is better to use password input field and show it in the way like https://stackoverflow.com/a/32149838

**Comment by denis-sokolov** [comment]
Thank you for your report.
Unfortunately, there is no way to securely implement that at the moment.
Most other extensions leak the master password to random websites, which is not acceptable.

This is mentioned on the support page in the options of the extension.
Also, #20, #27, #56.
